import React, { useState } from 'react';
import { 
  Plus, Trash2, Save, ArrowLeft, Image as ImageIcon, 
  Type, AlignLeft, Grid, Layout, Upload, Loader2, X, Link as LinkIcon
} from 'lucide-react';
import { Article, ArticleBlock, ArticleBlockType, ArticleImage } from '../types';
import { supabase } from '../supabaseClient';

interface ArticleConstructorProps {
  articles: Article[];
  onSave: () => void; // Callback to refresh data
}

const ArticleConstructor: React.FC<ArticleConstructorProps> = ({ articles, onSave }) => {
  const [view, setView] = useState<'list' | 'edit'>('list');
  const [currentArticle, setCurrentArticle] = useState<Partial<Article>>({});
  const [blocks, setBlocks] = useState<ArticleBlock[]>([]);
  const [isSaving, setIsSaving] = useState(false);
  const [uploadingImageId, setUploadingImageId] = useState<string | null>(null);
  
  // Состояние для переключения режима ввода (файл/ссылка) для каждой картинки: { "blockId-imgIndex": true }
  const [urlInputModes, setUrlInputModes] = useState<Record<string, boolean>>({});

  // --- Helpers ---

  const generateId = () => Math.random().toString(36).substr(2, 9);

  const startEdit = (article?: Article) => {
    if (article) {
      setCurrentArticle(article);
      setBlocks(article.content || []);
    } else {
      setCurrentArticle({ title: '', description: '' });
      setBlocks([]);
    }
    setView('edit');
  };

  const handleSave = async () => {
    if (!currentArticle.title) {
      alert("Введите название статьи");
      return;
    }

    setIsSaving(true);
    try {
      if (!supabase) throw new Error("No database connection");

      const payload = {
        title: currentArticle.title,
        description: currentArticle.description,
        content: blocks, // Supabase автоматически сериализует JSON
        url: currentArticle.url || `#article-${Date.now()}` // Генерируем заглушку, если нет
      };

      if (currentArticle.id) {
        // Update
        const { error } = await supabase
          .from('letter_shibari')
          .update(payload)
          .eq('id', currentArticle.id);
        if (error) throw error;
      } else {
        // Insert
        const { error } = await supabase
          .from('letter_shibari')
          .insert([payload]);
        if (error) throw error;
      }

      onSave();
      setView('list');
    } catch (e: any) {
      console.error("Error saving article:", e);
      
      // Extract error message safely
      let errorMessage = "Неизвестная ошибка";
      if (typeof e === 'string') {
          errorMessage = e;
      } else if (e instanceof Error) {
          errorMessage = e.message;
      } else if (typeof e === 'object' && e !== null) {
          errorMessage = e.message || e.error_description || e.details || JSON.stringify(e);
      }

      const repairSql = `
-- 1. Создаем таблицу, если её нет
create table if not exists public.letter_shibari (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text,
  description text,
  url text,
  content jsonb
);

-- 2. Добавляем колонки, если таблица была неполной
alter table public.letter_shibari add column if not exists title text;
alter table public.letter_shibari add column if not exists description text;
alter table public.letter_shibari add column if not exists url text;
alter table public.letter_shibari add column if not exists content jsonb;

-- 3. Настраиваем права доступа (RLS)
alter table public.letter_shibari enable row level security;

-- 4. Создаем политику для доступа всем (для демо-режима)
do $$
begin
  if not exists (select 1 from pg_policies where tablename = 'letter_shibari' and policyname = 'Allow all operations') then
    create policy "Allow all operations" on public.letter_shibari for all using (true) with check (true);
  end if;
end
$$;
      `.trim();

      // Обработка специфических ошибок Postgres/Supabase
      if (
          e?.code === '42P01' || // undefined_table
          e?.code === 'PGRST205' || 
          errorMessage.includes('relation "letter_shibari" does not exist')
      ) {
          console.log("SQL TO CREATE TABLE:", repairSql);
          alert(`Ошибка: Таблица не найдена.\n\nСкопируйте и выполните этот SQL в Supabase SQL Editor:\n\n${repairSql}`);
      } 
      else if (
          e?.code === '42703' || // undefined_column
          errorMessage.includes("column") || 
          errorMessage.includes("content")
      ) {
          console.log("SQL TO FIX COLUMNS:", repairSql);
          alert(`Ошибка структуры (нет колонок).\n\nВыполните SQL:\n\n${repairSql}`);
      } 
      else if (e?.code === 'PGRST204') {
          alert("ОШИБКА КЭША СХЕМЫ (PGRST204).\n\nВы изменили структуру таблицы, но API использует старый кэш.\n\nРЕШЕНИЕ:\n1. Откройте Supabase Dashboard.\n2. Перейдите в Settings -> API.\n3. Нажмите кнопку 'Reload Schema Cache'.\n4. Попробуйте сохранить снова.");
      }
      else if (e?.code === '42501') { // insufficient_privilege (RLS)
          console.log("SQL TO FIX RLS:", repairSql);
          alert(`Ошибка доступа (RLS).\n\nSupabase блокирует запись. Выполните SQL для настройки прав:\n\n${repairSql}`);
      } 
      else {
          alert(`Ошибка при сохранении: ${errorMessage}\n\nПопробуйте выполнить ремонтный SQL (см. консоль) или перезагрузить кэш схемы.`);
          console.log("GENERIC REPAIR SQL:", repairSql);
      }
    } finally {
      setIsSaving(false);
    }
  };

  const handleDelete = async (id: number) => {
    if (!window.confirm("Удалить статью? Это действие нельзя отменить.")) return;
    
    try {
      if (supabase) {
        const { error } = await supabase.from('letter_shibari').delete().eq('id', id);
        if (error) throw error;
        onSave();
      }
    } catch (e: any) {
      console.error(e);
      alert(`Ошибка удаления: ${e.message || JSON.stringify(e)}`);
    }
  };

  // --- Block Management ---

  const addBlock = (type: ArticleBlockType) => {
    const newBlock: ArticleBlock = {
      id: generateId(),
      type,
      content: '',
      title: '',
      images: []
    };

    // Pre-fill images array based on type
    if (type === 'image_1') newBlock.images = [{ url: '' }];
    if (type === 'image_2') newBlock.images = [{ url: '' }, { url: '' }];
    if (type === 'image_3') newBlock.images = [{ url: '' }, { url: '' }, { url: '' }];
    if (type === 'image_4') newBlock.images = [{ url: '' }, { url: '' }, { url: '' }, { url: '' }];

    setBlocks([...blocks, newBlock]);
  };

  const removeBlock = (id: string) => {
    setBlocks(blocks.filter(b => b.id !== id));
  };

  const updateBlock = (id: string, field: keyof ArticleBlock, value: any) => {
    setBlocks(blocks.map(b => b.id === id ? { ...b, [field]: value } : b));
  };

  // --- Image Upload ---

  const toggleUrlMode = (blockId: string, imageIndex: number) => {
      const key = `${blockId}-${imageIndex}`;
      setUrlInputModes(prev => ({ ...prev, [key]: !prev[key] }));
  };

  const updateImageUrl = (blockId: string, imageIndex: number, url: string) => {
      setBlocks(prev => prev.map(b => {
        if (b.id !== blockId) return b;
        const newImages = [...(b.images || [])];
        if (newImages[imageIndex]) {
            newImages[imageIndex] = { ...newImages[imageIndex], url };
        } else {
             newImages[imageIndex] = { url };
        }
        return { ...b, images: newImages };
      }));
  };

  const handleImageUpload = async (blockId: string, imageIndex: number, file: File) => {
    if (!supabase) return;
    
    const uniqueId = `${blockId}-${imageIndex}`;
    setUploadingImageId(uniqueId);

    try {
      const fileExt = file.name.split('.').pop();
      const fileName = `${Math.random().toString(36).substring(2)}.${fileExt}`;
      const filePath = `articles/${fileName}`;

      const { error: uploadError } = await supabase.storage
        .from('Enot') // Используем существующий бакет
        .upload(filePath, file);

      if (uploadError) throw uploadError;

      const { data } = supabase.storage.from('Enot').getPublicUrl(filePath);
      updateImageUrl(blockId, imageIndex, data.publicUrl);

    } catch (error: any) {
      console.error('Error uploading image:', error);
      if (error.message?.includes('row-level security') || error.code === '42501') {
          alert("Ошибка доступа к хранилищу (RLS). Загрузка файлов запрещена политиками безопасности Supabase. Пожалуйста, используйте кнопку 'Ссылка' для вставки URL изображения вручную.");
          // Автоматически переключаем на режим ссылки
          toggleUrlMode(blockId, imageIndex);
      } else {
          alert(`Ошибка загрузки: ${error.message || 'Неизвестная ошибка'}`);
      }
    } finally {
      setUploadingImageId(null);
    }
  };

  const updateCaption = (blockId: string, imageIndex: number, caption: string) => {
    setBlocks(prev => prev.map(b => {
      if (b.id !== blockId) return b;
      const newImages = [...(b.images || [])];
      if (newImages[imageIndex]) {
        newImages[imageIndex] = { ...newImages[imageIndex], caption };
      }
      return { ...b, images: newImages };
    }));
  };

  // --- Renders ---

  if (view === 'list') {
    return (
      <div className="space-y-6">
        <div className="flex justify-between items-center">
            <p className="text-neutral-400">Управление статьями курса.</p>
            <button 
                onClick={() => startEdit()}
                className="bg-red-700 hover:bg-red-600 text-white px-4 py-2 rounded-lg font-medium flex items-center gap-2 transition-colors"
            >
                <Plus className="w-4 h-4" /> Новая статья
            </button>
        </div>

        <div className="grid gap-4">
            {articles.map(article => (
                <div key={article.id} className="bg-neutral-900 border border-neutral-800 p-4 rounded-xl flex items-center justify-between hover:border-neutral-700 transition-colors">
                    <div>
                        <h4 className="font-bold text-white text-lg">{article.title || "Без названия"}</h4>
                        <p className="text-neutral-500 text-sm line-clamp-1">{article.description || "Нет описания"}</p>
                    </div>
                    <div className="flex items-center gap-2">
                         <button 
                            onClick={() => startEdit(article)}
                            className="p-2 bg-neutral-800 hover:bg-neutral-700 text-white rounded-lg transition-colors"
                         >
                            Ред.
                        </button>
                        <button 
                            onClick={() => handleDelete(article.id)}
                            className="p-2 bg-neutral-800 hover:bg-red-900/50 text-red-500 rounded-lg transition-colors"
                        >
                            <Trash2 className="w-4 h-4" />
                        </button>
                    </div>
                </div>
            ))}
            {articles.length === 0 && (
                <div className="text-center py-10 text-neutral-600 border border-dashed border-neutral-800 rounded-xl">
                    Статей пока нет. Создайте первую!
                </div>
            )}
        </div>
      </div>
    );
  }

  // --- Edit View ---

  return (
    <div className="flex flex-col h-full">
      {/* Edit Header */}
      <div className="flex items-center justify-between mb-6 pb-4 border-b border-neutral-800">
        <button onClick={() => setView('list')} className="text-neutral-400 hover:text-white flex items-center gap-2">
            <ArrowLeft className="w-4 h-4" /> Назад
        </button>
        <button 
            onClick={handleSave} 
            disabled={isSaving}
            className="bg-green-700 hover:bg-green-600 text-white px-6 py-2 rounded-lg font-medium flex items-center gap-2 disabled:opacity-50"
        >
            {isSaving ? <Loader2 className="w-4 h-4 animate-spin"/> : <Save className="w-4 h-4" />}
            Сохранить
        </button>
      </div>

      <div className="flex-1 overflow-y-auto pr-2 space-y-6">
        
        {/* Meta Data */}
        <div className="space-y-4 bg-neutral-900/50 p-4 rounded-xl border border-neutral-800">
            <input 
                value={currentArticle.title || ''}
                onChange={e => setCurrentArticle({...currentArticle, title: e.target.value})}
                placeholder="Название статьи (Заголовок)"
                className="w-full bg-transparent text-2xl md:text-3xl font-bold text-white placeholder-neutral-600 outline-none"
            />
            <textarea 
                value={currentArticle.description || ''}
                onChange={e => setCurrentArticle({...currentArticle, description: e.target.value})}
                placeholder="Лид (краткое описание для карточки)..."
                rows={2}
                className="w-full bg-transparent text-neutral-400 text-sm resize-none outline-none"
            />
        </div>

        {/* Blocks List */}
        <div className="space-y-4">
            {blocks.map((block, index) => (
                <div key={block.id} className="relative group bg-neutral-900 border border-neutral-800 rounded-xl p-4 hover:border-neutral-600 transition-colors">
                    <div className="absolute top-2 right-2 opacity-0 group-hover:opacity-100 transition-opacity flex gap-2">
                        <span className="text-xs text-neutral-600 uppercase bg-black px-2 py-1 rounded">{block.type}</span>
                        <button onClick={() => removeBlock(block.id)} className="text-red-500 hover:bg-red-900/30 p-1 rounded">
                            <Trash2 className="w-4 h-4" />
                        </button>
                    </div>

                    {/* Block Content Renderers */}
                    
                    {block.type === 'header' && (
                        <input 
                            value={block.content} 
                            onChange={e => updateBlock(block.id, 'content', e.target.value)}
                            placeholder="Крупный заголовок раздела"
                            className="w-full bg-transparent text-xl font-bold text-red-500 placeholder-neutral-700 outline-none"
                        />
                    )}

                    {(block.type === 'text_long' || block.type === 'text_short') && (
                        <div className="space-y-2">
                            <input 
                                value={block.title || ''} 
                                onChange={e => updateBlock(block.id, 'title', e.target.value)}
                                placeholder="Заголовок абзаца (необязательно)"
                                className="w-full bg-transparent font-bold text-neutral-300 placeholder-neutral-700 outline-none"
                            />
                            <textarea
                                value={block.content}
                                onChange={e => updateBlock(block.id, 'content', e.target.value)}
                                placeholder={block.type === 'text_long' ? "Длинный текст абзаца..." : "Короткий текст..."}
                                rows={block.type === 'text_long' ? 6 : 3}
                                className="w-full bg-neutral-950/50 p-3 rounded-lg text-neutral-300 placeholder-neutral-700 outline-none resize-y border border-neutral-800 focus:border-neutral-600"
                            />
                        </div>
                    )}

                    {block.type.startsWith('image_') && (
                        <div className="space-y-3">
                             <p className="text-xs text-neutral-500 font-bold uppercase mb-2">
                                {block.type === 'image_1' && 'Одна картинка (Горизонтально 3/4)'}
                                {block.type === 'image_2' && 'Две картинки рядом (3/4)'}
                                {block.type === 'image_3' && 'Три картинки в ряд'}
                                {block.type === 'image_4' && 'Сетка 4 картинки'}
                             </p>
                             <div className={`grid gap-4 ${
                                block.type === 'image_1' ? 'grid-cols-1 max-w-[75%]' : 
                                block.type === 'image_2' ? 'grid-cols-2 max-w-[75%]' :
                                block.type === 'image_3' ? 'grid-cols-1 md:grid-cols-3' :
                                'grid-cols-2 md:grid-cols-4'
                             }`}>
                                {block.images?.map((img, imgIdx) => {
                                    const inputModeKey = `${block.id}-${imgIdx}`;
                                    const isUrlMode = urlInputModes[inputModeKey];

                                    return (
                                        <div key={imgIdx} className="space-y-2">
                                            <div className="aspect-square md:aspect-video bg-neutral-950 rounded-lg border border-neutral-800 flex items-center justify-center relative overflow-hidden group/img">
                                                {img.url ? (
                                                    <>
                                                        <img src={img.url} className="w-full h-full object-cover" alt="" />
                                                        <div className="absolute inset-0 bg-black/50 opacity-0 group-hover/img:opacity-100 transition-opacity flex items-center justify-center gap-2">
                                                            <button 
                                                                onClick={() => updateImageUrl(block.id, imgIdx, '')}
                                                                className="bg-red-600 text-white p-2 rounded-full hover:bg-red-500 transition-colors"
                                                                title="Удалить"
                                                            >
                                                                <Trash2 className="w-4 h-4" />
                                                            </button>
                                                        </div>
                                                    </>
                                                ) : (
                                                    <div className="flex flex-col items-center gap-2 w-full px-4">
                                                        {isUrlMode ? (
                                                            <div className="w-full flex flex-col gap-2 animate-in fade-in zoom-in duration-200">
                                                                <input 
                                                                    autoFocus
                                                                    type="text" 
                                                                    placeholder="https://..."
                                                                    className="w-full bg-neutral-900 border border-neutral-700 rounded px-2 py-1 text-xs text-white outline-none focus:border-red-600"
                                                                    onKeyDown={(e) => {
                                                                        if (e.key === 'Enter') {
                                                                            updateImageUrl(block.id, imgIdx, e.currentTarget.value);
                                                                        }
                                                                    }}
                                                                    onBlur={(e) => {
                                                                        if(e.target.value) updateImageUrl(block.id, imgIdx, e.target.value);
                                                                    }}
                                                                />
                                                                <button onClick={() => toggleUrlMode(block.id, imgIdx)} className="text-[10px] text-neutral-500 hover:text-white underline">
                                                                    Вернуться к загрузке
                                                                </button>
                                                            </div>
                                                        ) : (
                                                            <>
                                                                <label className="cursor-pointer flex flex-col items-center text-neutral-600 hover:text-neutral-400 transition-colors">
                                                                    {uploadingImageId === inputModeKey ? (
                                                                        <Loader2 className="w-6 h-6 animate-spin" />
                                                                    ) : (
                                                                        <>
                                                                            <Upload className="w-6 h-6 mb-1" />
                                                                            <span className="text-[10px]">Загрузить</span>
                                                                        </>
                                                                    )}
                                                                    <input 
                                                                        type="file" 
                                                                        accept="image/*" 
                                                                        className="hidden" 
                                                                        onChange={(e) => {
                                                                            if (e.target.files?.[0]) handleImageUpload(block.id, imgIdx, e.target.files[0]);
                                                                        }}
                                                                    />
                                                                </label>
                                                                <button 
                                                                    onClick={() => toggleUrlMode(block.id, imgIdx)}
                                                                    className="flex items-center gap-1 text-[10px] text-neutral-600 hover:text-red-500 transition-colors mt-2"
                                                                >
                                                                    <LinkIcon className="w-3 h-3" /> Ссылка
                                                                </button>
                                                            </>
                                                        )}
                                                    </div>
                                                )}
                                            </div>
                                            <input 
                                                value={img.caption || ''}
                                                onChange={(e) => updateCaption(block.id, imgIdx, e.target.value)}
                                                placeholder="Подпись курсивом..."
                                                className="w-full bg-transparent text-xs text-neutral-500 italic text-center outline-none border-b border-transparent focus:border-neutral-700 pb-1"
                                            />
                                        </div>
                                    );
                                })}
                             </div>
                        </div>
                    )}

                </div>
            ))}
        </div>

        {/* Toolbar */}
        <div className="py-6 border-t border-neutral-800">
            <p className="text-xs text-neutral-500 uppercase font-bold mb-3 text-center">Добавить блок</p>
            <div className="flex flex-wrap gap-2 justify-center">
                <ToolBtn icon={Type} label="Заголовок" onClick={() => addBlock('header')} />
                <ToolBtn icon={AlignLeft} label="Длинный текст" onClick={() => addBlock('text_long')} />
                <ToolBtn icon={AlignLeft} label="Короткий текст" onClick={() => addBlock('text_short')} />
                <div className="w-px h-8 bg-neutral-800 mx-2" />
                <ToolBtn icon={ImageIcon} label="1 Фото" onClick={() => addBlock('image_1')} />
                <ToolBtn icon={Layout} label="2 Фото" onClick={() => addBlock('image_2')} />
                <ToolBtn icon={Grid} label="3 Фото (Ряд)" onClick={() => addBlock('image_3')} />
                <ToolBtn icon={Grid} label="4 Фото (Сетка)" onClick={() => addBlock('image_4')} />
            </div>
        </div>
      </div>
    </div>
  );
};

const ToolBtn: React.FC<{ icon: any, label: string, onClick: () => void }> = ({ icon: Icon, label, onClick }) => (
    <button 
        onClick={onClick}
        className="flex flex-col items-center justify-center p-3 w-20 h-20 bg-neutral-900 border border-neutral-800 rounded-lg hover:bg-neutral-800 hover:border-red-900/50 hover:text-white text-neutral-500 transition-all gap-2"
    >
        <Icon className="w-5 h-5" />
        <span className="text-[10px] text-center leading-tight">{label}</span>
    </button>
);

export default ArticleConstructor;