import React, { useState } from 'react';
import { Plus, Trash2, Save, ArrowLeft, Loader2, Video, Database, PenTool, LayoutList, HelpCircle, Image as ImageIcon, Upload, X } from 'lucide-react';
import { Course, ProductFAQ } from '../types';
import { supabase } from '../supabaseClient';
import { INITIAL_COURSES } from '../constants';

interface CourseManagerProps {
  courses: Course[];
  onSave: () => void;
}

const CourseManager: React.FC<CourseManagerProps> = ({ courses, onSave }) => {
  const [view, setView] = useState<'list' | 'edit'>('list');
  const [currentCourse, setCurrentCourse] = useState<Partial<Course>>({});
  const [isSaving, setIsSaving] = useState(false);
  const [uploading, setUploading] = useState(false);

  // --- Seed Logic ---
  const handleSeedCourses = async () => {
      if (!window.confirm("Это загрузит демо-курсы из констант в базу данных. Продолжить?")) return;
      
      setIsSaving(true);
      try {
          if (!supabase) throw new Error("Нет соединения с базой");

          const coursesToInsert = INITIAL_COURSES.map(({ id, ...rest }) => ({
              ...rest,
              modules: rest.modules || [],
              faq: rest.faq || []
          }));

          const { error } = await supabase
            .from('kurs_market_shibari')
            .insert(coursesToInsert);

          if (error) throw error;
          
          alert("Курсы успешно загружены!");
          onSave(); 
      } catch (e: any) {
          console.error(e);
          alert("Ошибка импорта: " + e.message);
      } finally {
          setIsSaving(false);
      }
  };

  const startEdit = (course?: Course) => {
    if (course) {
      setCurrentCourse(course);
    } else {
      setCurrentCourse({
        title: '',
        author: '',
        description_short: '',
        description_long: '',
        price: 0,
        video_url: '',
        image_url: '',
        modules: [],
        faq: []
      });
    }
    setView('edit');
  };

  const handleSave = async () => {
    if (!currentCourse.title) {
      alert("Введите название курса");
      return;
    }

    setIsSaving(true);
    try {
      if (!supabase) throw new Error("No database connection");

      const payload = {
        title: currentCourse.title,
        author: currentCourse.author,
        description_short: currentCourse.description_short,
        description_long: currentCourse.description_long,
        price: currentCourse.price,
        video_url: currentCourse.video_url,
        image_url: currentCourse.image_url,
        modules: currentCourse.modules || [],
        faq: currentCourse.faq || []
      };

      if (currentCourse.id) {
        const { error } = await supabase
          .from('kurs_market_shibari')
          .update(payload)
          .eq('id', currentCourse.id);
        if (error) throw error;
      } else {
        const { error } = await supabase
          .from('kurs_market_shibari')
          .insert([payload]);
        if (error) throw error;
      }

      onSave();
      setView('list');
    } catch (e: any) {
      console.error("Error saving course:", e);
      const repairSql = `
create table if not exists public.kurs_market_shibari (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  author text,
  description_short text,
  description_long text,
  video_url text,
  image_url text,
  price numeric default 0,
  modules text[] default '{}',
  faq jsonb default '[]'
);
alter table public.kurs_market_shibari enable row level security;
create policy "Allow all operations" on public.kurs_market_shibari for all using (true) with check (true);
      `.trim();
      alert(`Ошибка сохранения: ${e.message}\nSQL для создания таблицы:\n\n${repairSql}`);
    } finally {
      setIsSaving(false);
    }
  };

  const handleDelete = async (id: number) => {
    if (!window.confirm("Удалить курс?")) return;
    try {
      if (supabase) {
        await supabase.from('kurs_market_shibari').delete().eq('id', id);
        onSave();
      }
    } catch (e) {
      console.error(e);
    }
  };

  const handleImageUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    if (!e.target.files || !e.target.files.length || !supabase) return;
    setUploading(true);
    
    try {
        const file = e.target.files[0];
        const fileExt = file.name.split('.').pop();
        const fileName = `courses/${Math.random().toString(36).substring(2)}.${fileExt}`;
        
        const { error } = await supabase.storage.from('Enot').upload(fileName, file);
        if (error) throw error;
        
        const { data } = supabase.storage.from('Enot').getPublicUrl(fileName);
        setCurrentCourse(prev => ({ ...prev, image_url: data.publicUrl }));
    } catch (err: any) {
        alert("Ошибка загрузки фото: " + err.message);
    } finally {
        setUploading(false);
    }
  };

  // --- Helper Editors ---

  const addModule = () => {
      setCurrentCourse(prev => ({
          ...prev,
          modules: [...(prev.modules || []), '']
      }));
  };

  const updateModule = (index: number, val: string) => {
      setCurrentCourse(prev => {
          const newModules = [...(prev.modules || [])];
          newModules[index] = val;
          return { ...prev, modules: newModules };
      });
  };

  const removeModule = (index: number) => {
      setCurrentCourse(prev => ({
          ...prev,
          modules: prev.modules?.filter((_, i) => i !== index)
      }));
  };

  const addFaq = () => {
    setCurrentCourse(prev => ({
        ...prev,
        faq: [...(prev.faq || []), { question: '', answer: '' }]
    }));
  };

  const updateFaq = (index: number, field: keyof ProductFAQ, value: string) => {
    setCurrentCourse(prev => {
        const newFaq = [...(prev.faq || [])];
        newFaq[index] = { ...newFaq[index], [field]: value };
        return { ...prev, faq: newFaq };
    });
  };

  const removeFaq = (index: number) => {
    setCurrentCourse(prev => ({
        ...prev,
        faq: prev.faq?.filter((_, i) => i !== index)
    }));
  };

  if (view === 'list') {
    return (
      <div className="space-y-6">
         <div className="flex justify-between items-center">
            <p className="text-neutral-400">Управление видеокурсами.</p>
            <div className="flex gap-2">
                {courses.length === 0 && (
                    <button 
                        onClick={handleSeedCourses}
                        disabled={isSaving}
                        className="bg-neutral-800 hover:bg-neutral-700 text-neutral-300 px-4 py-2 rounded-lg font-medium flex items-center gap-2 transition-colors border border-neutral-700"
                    >
                        {isSaving ? <Loader2 className="w-4 h-4 animate-spin"/> : <Database className="w-4 h-4" />} 
                        Загрузить демо
                    </button>
                )}
                <button 
                    onClick={() => startEdit()}
                    className="bg-red-700 hover:bg-red-600 text-white px-4 py-2 rounded-lg font-medium flex items-center gap-2 transition-colors"
                >
                    <Plus className="w-4 h-4" /> Добавить курс
                </button>
            </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            {courses.map(c => (
                <div key={c.id} className="bg-neutral-900 border border-neutral-800 rounded-xl overflow-hidden flex flex-col group relative hover:border-neutral-600 transition-colors p-4">
                     <div className="flex justify-between items-start mb-2">
                        <h4 className="font-bold text-white text-lg line-clamp-1">{c.title}</h4>
                        <div className="flex gap-2">
                            <button onClick={() => startEdit(c)} className="p-2 bg-neutral-800 text-neutral-300 rounded hover:text-white border border-neutral-700" title="Редактировать">
                                <PenTool className="w-4 h-4"/>
                            </button>
                            <button onClick={() => handleDelete(c.id)} className="p-2 bg-red-900/20 text-red-500 rounded hover:bg-red-900/40 border border-red-900/30" title="Удалить">
                                <Trash2 className="w-4 h-4"/>
                            </button>
                        </div>
                     </div>
                     <p className="text-neutral-500 text-sm mb-4 line-clamp-2">{c.description_short}</p>
                     <div className="mt-auto flex justify-between items-center border-t border-neutral-800 pt-3">
                         <span className="text-xs font-medium text-neutral-400">{c.author}</span>
                         <span className="text-sm font-mono font-bold text-white">${c.price}</span>
                     </div>
                </div>
            ))}
        </div>
      </div>
    );
  }

  return (
    <div className="flex flex-col h-full space-y-6">
      <div className="flex items-center justify-between border-b border-neutral-800 pb-4">
         <button onClick={() => setView('list')} className="text-neutral-400 hover:text-white flex items-center gap-2">
            <ArrowLeft className="w-4 h-4" /> Назад
         </button>
         <button 
            onClick={handleSave} 
            disabled={isSaving}
            className="bg-green-700 hover:bg-green-600 text-white px-6 py-2 rounded-lg font-medium flex items-center gap-2 disabled:opacity-50"
        >
            {isSaving ? <Loader2 className="w-4 h-4 animate-spin"/> : <Save className="w-4 h-4" />}
            Сохранить
        </button>
      </div>

      <div className="flex-1 overflow-y-auto space-y-6 pr-2">
          {/* Main Info */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div className="space-y-4">
                  <input 
                    value={currentCourse.title || ''}
                    onChange={e => setCurrentCourse({...currentCourse, title: e.target.value})}
                    placeholder="Название курса"
                    className="w-full bg-neutral-900 border border-neutral-800 rounded-lg px-4 py-3 text-white focus:border-red-600 outline-none"
                  />
                  <div className="flex gap-4">
                      <input 
                        value={currentCourse.author || ''}
                        onChange={e => setCurrentCourse({...currentCourse, author: e.target.value})}
                        placeholder="Автор"
                        className="flex-1 bg-neutral-900 border border-neutral-800 rounded-lg px-4 py-3 text-white focus:border-red-600 outline-none"
                      />
                      <input 
                        type="number"
                        value={currentCourse.price || ''}
                        onChange={e => setCurrentCourse({...currentCourse, price: parseFloat(e.target.value)})}
                        placeholder="Цена ($)"
                        className="w-32 bg-neutral-900 border border-neutral-800 rounded-lg px-4 py-3 text-white focus:border-red-600 outline-none"
                      />
                  </div>
                  
                  {/* Media Inputs */}
                  <div className="space-y-4 border-t border-neutral-800 pt-4 mt-2">
                       <label className="text-xs font-bold text-neutral-500 uppercase flex items-center gap-2"><ImageIcon className="w-4 h-4"/> Обложка курса</label>
                       <div className="flex items-center gap-4">
                           <div className="w-24 h-16 bg-neutral-800 rounded overflow-hidden border border-neutral-700 flex items-center justify-center">
                               {currentCourse.image_url ? (
                                   <img src={currentCourse.image_url} className="w-full h-full object-cover" alt="Preview"/>
                               ) : (
                                   <ImageIcon className="w-6 h-6 text-neutral-600"/>
                               )}
                           </div>
                           <label className="cursor-pointer bg-neutral-800 hover:bg-neutral-700 text-white px-4 py-2 rounded text-sm flex items-center gap-2 transition-colors">
                               {uploading ? <Loader2 className="w-4 h-4 animate-spin"/> : <Upload className="w-4 h-4"/>}
                               Загрузить фото
                               <input type="file" accept="image/*" className="hidden" onChange={handleImageUpload} disabled={uploading}/>
                           </label>
                           {currentCourse.image_url && (
                               <button onClick={() => setCurrentCourse({...currentCourse, image_url: ''})} className="text-red-500 hover:text-red-400 p-2"><X className="w-5 h-5"/></button>
                           )}
                       </div>
                  </div>

                  <input 
                    value={currentCourse.video_url || ''}
                    onChange={e => setCurrentCourse({...currentCourse, video_url: e.target.value})}
                    placeholder="Ссылка на промо-видео (YouTube)"
                    className="w-full bg-neutral-900 border border-neutral-800 rounded-lg px-4 py-3 text-white focus:border-red-600 outline-none text-sm"
                  />
              </div>
              
              <div className="space-y-4">
                   <textarea 
                    value={currentCourse.description_short || ''}
                    onChange={e => setCurrentCourse({...currentCourse, description_short: e.target.value})}
                    placeholder="Краткое описание (для карточки)"
                    rows={3}
                    className="w-full bg-neutral-900 border border-neutral-800 rounded-lg px-4 py-3 text-white focus:border-red-600 outline-none resize-none"
                  />
                  <textarea 
                    value={currentCourse.description_long || ''}
                    onChange={e => setCurrentCourse({...currentCourse, description_long: e.target.value})}
                    placeholder="Полное описание курса (Лендинг)..."
                    rows={5}
                    className="w-full bg-neutral-900 border border-neutral-800 rounded-lg px-4 py-3 text-white focus:border-red-600 outline-none"
                  />
              </div>
          </div>

          {/* Modules Editor */}
          <div className="bg-neutral-900/50 border border-neutral-800 rounded-xl p-4">
              <div className="flex items-center justify-between mb-4">
                  <h4 className="font-bold text-white text-sm flex items-center gap-2"><LayoutList className="w-4 h-4"/> Модули курса (Минимум 8)</h4>
                  <button onClick={addModule} className="text-xs text-red-500 hover:text-red-400 font-bold flex items-center gap-1"><Plus className="w-3 h-3"/> Добавить модуль</button>
              </div>
              <div className="space-y-2">
                  {(currentCourse.modules || []).map((mod, idx) => (
                      <div key={idx} className="flex gap-2 items-center">
                          <span className="text-neutral-500 text-xs w-6">{idx + 1}.</span>
                          <input 
                            value={mod}
                            onChange={e => updateModule(idx, e.target.value)}
                            placeholder={`Название модуля ${idx + 1}`}
                            className="flex-1 bg-neutral-900 border border-neutral-700 rounded px-3 py-2 text-sm text-white outline-none"
                          />
                          <button onClick={() => removeModule(idx)} className="text-neutral-500 hover:text-red-500"><Trash2 className="w-4 h-4"/></button>
                      </div>
                  ))}
                  {!currentCourse.modules?.length && <div className="text-neutral-500 text-sm text-center py-2">Модулей нет</div>}
              </div>
          </div>

          {/* FAQ Editor */}
          <div className="bg-neutral-900/50 border border-neutral-800 rounded-xl p-4">
              <div className="flex items-center justify-between mb-4">
                  <h4 className="font-bold text-white text-sm flex items-center gap-2"><HelpCircle className="w-4 h-4"/> Частые вопросы (FAQ)</h4>
                  <button onClick={addFaq} className="text-xs text-red-500 hover:text-red-400 font-bold flex items-center gap-1"><Plus className="w-3 h-3"/> Добавить вопрос</button>
              </div>
              <div className="space-y-4">
                  {(currentCourse.faq || []).map((item, idx) => (
                      <div key={idx} className="flex flex-col gap-2 border-b border-neutral-800 pb-4 last:border-0 last:pb-0">
                          <div className="flex gap-2">
                              <input 
                                value={item.question}
                                onChange={e => updateFaq(idx, 'question', e.target.value)}
                                placeholder="Вопрос"
                                className="flex-1 bg-neutral-900 border border-neutral-700 rounded px-3 py-2 text-sm text-white outline-none"
                              />
                              <button onClick={() => removeFaq(idx)} className="text-neutral-500 hover:text-red-500"><Trash2 className="w-4 h-4"/></button>
                          </div>
                          <textarea 
                            value={item.answer}
                            onChange={e => updateFaq(idx, 'answer', e.target.value)}
                            placeholder="Ответ"
                            rows={2}
                            className="w-full bg-neutral-900 border border-neutral-700 rounded px-3 py-2 text-sm text-neutral-300 outline-none resize-none"
                          />
                      </div>
                  ))}
              </div>
          </div>
      </div>
    </div>
  );
};

export default CourseManager;