
import React, { useState } from 'react';
import { Plus, Trash2, Save, Calendar, Loader2, MapPin, Database, Image as ImageIcon } from 'lucide-react';
import { AppEvent } from '../types';
import { supabase } from '../supabaseClient';
import { INITIAL_EVENTS } from '../constants';

interface EventsManagerProps {
  events: AppEvent[];
  onSave: () => void;
}

const EventsManager: React.FC<EventsManagerProps> = ({ events, onSave }) => {
  const [view, setView] = useState<'list' | 'edit'>('list');
  const [currentEvent, setCurrentEvent] = useState<Partial<AppEvent>>({});
  const [isSaving, setIsSaving] = useState(false);

  const repairSql = `
CREATE TABLE IF NOT EXISTS public.event_shibari (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title text NOT NULL,
    description text,
    date text NOT NULL,
    time text,
    location text,
    image_url text,
    price text,
    registration_url text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

ALTER TABLE public.event_shibari ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'event_shibari' AND policyname = 'Allow all') THEN
    CREATE POLICY "Allow all" ON public.event_shibari FOR ALL USING (true) WITH CHECK (true);
  END IF;
END $$;
  `.trim();

  const handleSeed = async () => {
      if (!window.confirm("Загрузить демо-события?")) return;
      setIsSaving(true);
      try {
          if (!supabase) throw new Error("No DB");
          const seedData = INITIAL_EVENTS.map(({ id, ...rest }) => rest);
          const { error } = await supabase.from('event_shibari').insert(seedData);
          if (error) throw error;
          alert("События загружены!");
          onSave();
      } catch (e: any) {
          console.error(e);
          alert(`Ошибка: ${e.message}\nSQL:\n${repairSql}`);
      } finally {
          setIsSaving(false);
      }
  };

  const startEdit = (event?: AppEvent) => {
    if (event) {
      setCurrentEvent(event);
    } else {
      setCurrentEvent({
        title: '',
        description: '',
        date: new Date().toISOString().split('T')[0],
        time: '19:00',
        location: '',
        price: '',
        registration_url: '',
        image_url: ''
      });
    }
    setView('edit');
  };

  const handleSave = async () => {
    if (!currentEvent.title || !currentEvent.date) {
      alert("Название и дата обязательны");
      return;
    }

    setIsSaving(true);
    try {
      if (!supabase) throw new Error("No database connection");

      const payload = {
        title: currentEvent.title,
        description: currentEvent.description,
        date: currentEvent.date,
        time: currentEvent.time,
        location: currentEvent.location,
        image_url: currentEvent.image_url,
        price: currentEvent.price,
        registration_url: currentEvent.registration_url
      };

      if (currentEvent.id) {
        const { error } = await supabase
          .from('event_shibari')
          .update(payload)
          .eq('id', currentEvent.id);
        if (error) throw error;
      } else {
        const { error } = await supabase
          .from('event_shibari')
          .insert([payload]);
        if (error) throw error;
      }

      onSave();
      setView('list');
    } catch (e: any) {
      console.error(e);
      alert(`Ошибка сохранения: ${e.message}\nSQL:\n${repairSql}`);
    } finally {
      setIsSaving(false);
    }
  };

  const handleDelete = async (id: number) => {
    if (!window.confirm("Удалить событие?")) return;
    try {
      if (supabase) {
        await supabase.from('event_shibari').delete().eq('id', id);
        onSave();
      }
    } catch (e) {
      console.error(e);
    }
  };

  if (view === 'list') {
    return (
      <div className="space-y-6">
         <div className="flex justify-between items-center bg-neutral-900/50 p-4 rounded-xl border border-neutral-800">
            <div>
                <p className="text-white font-bold">Управление афишей</p>
                <p className="text-neutral-500 text-sm">Предстоящие мероприятия.</p>
            </div>
            <div className="flex gap-2">
                {events.length === 0 && (
                    <button 
                        onClick={handleSeed}
                        disabled={isSaving}
                        className="bg-neutral-800 hover:bg-neutral-700 text-neutral-300 px-4 py-2 rounded-lg font-medium flex items-center gap-2 transition-colors border border-neutral-700 text-sm"
                    >
                        {isSaving ? <Loader2 className="w-4 h-4 animate-spin"/> : <Database className="w-4 h-4" />} 
                        Загрузить демо
                    </button>
                )}
                <button 
                    onClick={() => startEdit()}
                    className="bg-red-700 hover:bg-red-600 text-white px-4 py-2 rounded-lg font-medium flex items-center gap-2 transition-colors"
                >
                    <Plus className="w-4 h-4" /> Добавить событие
                </button>
            </div>
        </div>

        <div className="grid gap-3">
            {events.map(ev => (
                <div key={ev.id} className="bg-neutral-900 border border-neutral-800 p-4 rounded-xl flex items-center justify-between hover:border-neutral-700 transition-colors">
                    <div className="flex items-center gap-4">
                        <div className="bg-neutral-950 px-3 py-2 rounded border border-neutral-800 text-center min-w-[60px]">
                            <div className="text-xs text-neutral-500 font-bold uppercase">{ev.date.split('-')[1]}/{ev.date.split('-')[2]}</div>
                            <div className="text-white font-bold">{ev.time}</div>
                        </div>
                        <div>
                            <h4 className="font-bold text-white text-sm">{ev.title}</h4>
                            <div className="flex items-center gap-2 text-xs text-neutral-500 mt-0.5">
                                <MapPin className="w-3 h-3"/> {ev.location || 'Online'}
                                <span className="text-neutral-700">|</span>
                                <span className="text-neutral-400">{ev.price || 'Free'}</span>
                            </div>
                        </div>
                    </div>
                    <div className="flex gap-2">
                        <button onClick={() => startEdit(ev)} className="p-2 bg-neutral-800 hover:bg-neutral-700 text-white rounded-lg transition-colors">Ред.</button>
                        <button onClick={() => handleDelete(ev.id)} className="p-2 bg-neutral-800 hover:bg-red-900/50 text-red-500 rounded-lg transition-colors"><Trash2 className="w-4 h-4"/></button>
                    </div>
                </div>
            ))}
            {events.length === 0 && <div className="text-center text-neutral-600 py-10">Афиша пуста</div>}
        </div>
      </div>
    );
  }

  return (
    <div className="flex flex-col h-full space-y-6">
        <div className="flex items-center justify-between border-b border-neutral-800 pb-4">
             <button onClick={() => setView('list')} className="text-neutral-400 hover:text-white flex items-center gap-2 px-3 py-1 bg-neutral-800 rounded">Назад</button>
             <button onClick={handleSave} disabled={isSaving} className="bg-green-700 hover:bg-green-600 text-white px-6 py-2 rounded-lg font-medium flex items-center gap-2 disabled:opacity-50">
                {isSaving ? <Loader2 className="w-4 h-4 animate-spin"/> : <Save className="w-4 h-4" />} Сохранить
            </button>
        </div>

        <div className="space-y-4 max-w-2xl mx-auto w-full">
            <div className="space-y-2">
                <label className="text-xs text-neutral-500 font-bold uppercase">Название мероприятия</label>
                <input 
                    value={currentEvent.title || ''}
                    onChange={e => setCurrentEvent({...currentEvent, title: e.target.value})}
                    placeholder="Например: Веревочный Джем"
                    className="w-full bg-neutral-900 border border-neutral-800 rounded-lg px-4 py-3 text-white focus:border-red-600 outline-none"
                />
            </div>
            
            <div className="grid grid-cols-2 gap-4">
                <div className="space-y-2">
                    <label className="text-xs text-neutral-500 font-bold uppercase">Дата</label>
                    <input 
                        type="date"
                        value={currentEvent.date || ''}
                        onChange={e => setCurrentEvent({...currentEvent, date: e.target.value})}
                        className="w-full bg-neutral-900 border border-neutral-800 rounded-lg px-4 py-3 text-white focus:border-red-600 outline-none"
                    />
                </div>
                <div className="space-y-2">
                    <label className="text-xs text-neutral-500 font-bold uppercase">Время</label>
                    <input 
                        type="time"
                        value={currentEvent.time || ''}
                        onChange={e => setCurrentEvent({...currentEvent, time: e.target.value})}
                        className="w-full bg-neutral-900 border border-neutral-800 rounded-lg px-4 py-3 text-white focus:border-red-600 outline-none"
                    />
                </div>
            </div>

            <div className="space-y-2">
                <label className="text-xs text-neutral-500 font-bold uppercase">Место проведения</label>
                <input 
                    value={currentEvent.location || ''}
                    onChange={e => setCurrentEvent({...currentEvent, location: e.target.value})}
                    placeholder="Город, Улица, Студия"
                    className="w-full bg-neutral-900 border border-neutral-800 rounded-lg px-4 py-3 text-white focus:border-red-600 outline-none"
                />
            </div>

            <div className="grid grid-cols-2 gap-4">
                <div className="space-y-2">
                    <label className="text-xs text-neutral-500 font-bold uppercase">Цена</label>
                    <input 
                        value={currentEvent.price || ''}
                        onChange={e => setCurrentEvent({...currentEvent, price: e.target.value})}
                        placeholder="500 руб / Бесплатно"
                        className="w-full bg-neutral-900 border border-neutral-800 rounded-lg px-4 py-3 text-white focus:border-red-600 outline-none"
                    />
                </div>
                 <div className="space-y-2">
                    <label className="text-xs text-neutral-500 font-bold uppercase">Ссылка на регистрацию</label>
                    <input 
                        value={currentEvent.registration_url || ''}
                        onChange={e => setCurrentEvent({...currentEvent, registration_url: e.target.value})}
                        placeholder="https://t.me/..."
                        className="w-full bg-neutral-900 border border-neutral-800 rounded-lg px-4 py-3 text-white focus:border-red-600 outline-none"
                    />
                </div>
            </div>

            <div className="space-y-2">
                <label className="text-xs text-neutral-500 font-bold uppercase">Описание</label>
                <textarea 
                    value={currentEvent.description || ''}
                    onChange={e => setCurrentEvent({...currentEvent, description: e.target.value})}
                    rows={4}
                    placeholder="Подробности мероприятия..."
                    className="w-full bg-neutral-900 border border-neutral-800 rounded-lg px-4 py-3 text-white focus:border-red-600 outline-none resize-none"
                />
            </div>

            <div className="space-y-2">
                <label className="text-xs text-neutral-500 font-bold uppercase flex items-center gap-2"><ImageIcon className="w-3 h-3"/> Изображение (URL)</label>
                <input 
                    value={currentEvent.image_url || ''}
                    onChange={e => setCurrentEvent({...currentEvent, image_url: e.target.value})}
                    placeholder="https://..."
                    className="w-full bg-neutral-900 border border-neutral-800 rounded-lg px-4 py-3 text-white focus:border-red-600 outline-none"
                />
            </div>
        </div>
    </div>
  );
};

export default EventsManager;
