
import React, { useState } from 'react';
import { Plus, Trash2, Save, Database, Scroll, Loader2, Calendar } from 'lucide-react';
import { HistoryEvent } from '../types';
import { supabase } from '../supabaseClient';
import { INITIAL_HISTORY } from '../constants';

interface HistoryManagerProps {
  events: HistoryEvent[];
  onSave: () => void;
}

const HistoryManager: React.FC<HistoryManagerProps> = ({ events, onSave }) => {
  const [view, setView] = useState<'list' | 'edit'>('list');
  const [currentEvent, setCurrentEvent] = useState<Partial<HistoryEvent>>({});
  const [isSaving, setIsSaving] = useState(false);

  const repairSql = `
CREATE TABLE IF NOT EXISTS public.history_shibari (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date_display text,
    title_ru text,
    title_en text,
    description_ru text,
    description_en text,
    image_url text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

ALTER TABLE public.history_shibari ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'history_shibari' AND policyname = 'Allow all') THEN
    CREATE POLICY "Allow all" ON public.history_shibari FOR ALL USING (true) WITH CHECK (true);
  END IF;
END $$;
  `.trim();

  const handleSeed = async () => {
      if (!window.confirm("Это загрузит демо-историю в базу. Продолжить?")) return;
      setIsSaving(true);
      try {
          if (!supabase) throw new Error("No DB");
          
          const seedData = INITIAL_HISTORY.map(({ id, ...rest }) => rest);
          const { error } = await supabase.from('history_shibari').insert(seedData);
          if (error) throw error;

          alert("История загружена!");
          onSave();
      } catch (e: any) {
          console.error(e);
          alert(`Ошибка: ${e.message}\nSQL:\n${repairSql}`);
      } finally {
          setIsSaving(false);
      }
  };

  const startEdit = (event?: HistoryEvent) => {
    if (event) {
      setCurrentEvent(event);
    } else {
      setCurrentEvent({
        date_display: '',
        title_ru: '',
        title_en: '',
        description_ru: '',
        description_en: '',
        image_url: ''
      });
    }
    setView('edit');
  };

  const handleSave = async () => {
    if (!currentEvent.date_display || !currentEvent.title_ru) {
      alert("Заполните дату и заголовок (RU)");
      return;
    }

    setIsSaving(true);
    try {
      if (!supabase) throw new Error("No database connection");

      const payload = {
        date_display: currentEvent.date_display,
        title_ru: currentEvent.title_ru,
        title_en: currentEvent.title_en,
        description_ru: currentEvent.description_ru,
        description_en: currentEvent.description_en,
        image_url: currentEvent.image_url
      };

      if (currentEvent.id) {
        const { error } = await supabase
          .from('history_shibari')
          .update(payload)
          .eq('id', currentEvent.id);
        if (error) throw error;
      } else {
        const { error } = await supabase
          .from('history_shibari')
          .insert([payload]);
        if (error) throw error;
      }

      onSave();
      setView('list');
    } catch (e: any) {
      console.error(e);
      alert(`Ошибка сохранения: ${e.message}\nSQL:\n${repairSql}`);
    } finally {
      setIsSaving(false);
    }
  };

  const handleDelete = async (id: number) => {
    if (!window.confirm("Удалить событие?")) return;
    try {
      if (supabase) {
        await supabase.from('history_shibari').delete().eq('id', id);
        onSave();
      }
    } catch (e) {
      console.error(e);
    }
  };

  if (view === 'list') {
    return (
      <div className="space-y-6">
         <div className="flex justify-between items-center bg-neutral-900/50 p-4 rounded-xl border border-neutral-800">
            <div>
                <p className="text-white font-bold">Хронология событий</p>
                <p className="text-neutral-500 text-sm">Управление исторической справкой.</p>
            </div>
            <div className="flex gap-2">
                {events.length === 0 && (
                    <button 
                        onClick={handleSeed}
                        disabled={isSaving}
                        className="bg-neutral-800 hover:bg-neutral-700 text-neutral-300 px-4 py-2 rounded-lg font-medium flex items-center gap-2 transition-colors border border-neutral-700 text-sm"
                    >
                        {isSaving ? <Loader2 className="w-4 h-4 animate-spin"/> : <Database className="w-4 h-4" />} 
                        Загрузить демо
                    </button>
                )}
                <button 
                    onClick={() => startEdit()}
                    className="bg-red-700 hover:bg-red-600 text-white px-4 py-2 rounded-lg font-medium flex items-center gap-2 transition-colors"
                >
                    <Plus className="w-4 h-4" /> Добавить событие
                </button>
            </div>
        </div>

        <div className="space-y-3">
            {events.map(ev => (
                <div key={ev.id} className="bg-neutral-900 border border-neutral-800 p-4 rounded-xl flex items-center justify-between hover:border-neutral-700 transition-colors">
                    <div className="flex items-center gap-4">
                        <span className="font-mono text-red-500 font-bold text-sm bg-neutral-950 px-2 py-1 rounded border border-neutral-800">{ev.date_display}</span>
                        <div>
                            <h4 className="font-bold text-white text-sm">{ev.title_ru}</h4>
                            <p className="text-neutral-500 text-xs line-clamp-1">{ev.description_ru}</p>
                        </div>
                    </div>
                    <div className="flex gap-2">
                        <button onClick={() => startEdit(ev)} className="p-2 bg-neutral-800 hover:bg-neutral-700 text-white rounded-lg transition-colors">Ред.</button>
                        <button onClick={() => handleDelete(ev.id)} className="p-2 bg-neutral-800 hover:bg-red-900/50 text-red-500 rounded-lg transition-colors"><Trash2 className="w-4 h-4"/></button>
                    </div>
                </div>
            ))}
            {events.length === 0 && <div className="text-center text-neutral-600 py-10">Список пуст</div>}
        </div>
      </div>
    );
  }

  return (
    <div className="flex flex-col h-full space-y-6">
        <div className="flex items-center justify-between border-b border-neutral-800 pb-4">
             <button onClick={() => setView('list')} className="text-neutral-400 hover:text-white flex items-center gap-2 px-3 py-1 bg-neutral-800 rounded">Назад</button>
             <button onClick={handleSave} disabled={isSaving} className="bg-green-700 hover:bg-green-600 text-white px-6 py-2 rounded-lg font-medium flex items-center gap-2 disabled:opacity-50">
                {isSaving ? <Loader2 className="w-4 h-4 animate-spin"/> : <Save className="w-4 h-4" />} Сохранить
            </button>
        </div>

        <div className="space-y-4 max-w-2xl mx-auto w-full">
            <div className="space-y-2">
                <label className="text-xs text-neutral-500 font-bold uppercase">Дата (Отображаемая)</label>
                <input 
                    value={currentEvent.date_display || ''}
                    onChange={e => setCurrentEvent({...currentEvent, date_display: e.target.value})}
                    placeholder="Например: 1400-1600 или 2005"
                    className="w-full bg-neutral-900 border border-neutral-800 rounded-lg px-4 py-3 text-white focus:border-red-600 outline-none"
                />
            </div>
            
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div className="space-y-2">
                    <label className="text-xs text-neutral-500 font-bold uppercase">Заголовок (RU)</label>
                    <input 
                        value={currentEvent.title_ru || ''}
                        onChange={e => setCurrentEvent({...currentEvent, title_ru: e.target.value})}
                        className="w-full bg-neutral-900 border border-neutral-800 rounded-lg px-4 py-3 text-white focus:border-red-600 outline-none"
                    />
                </div>
                <div className="space-y-2">
                    <label className="text-xs text-neutral-500 font-bold uppercase">Заголовок (EN)</label>
                    <input 
                        value={currentEvent.title_en || ''}
                        onChange={e => setCurrentEvent({...currentEvent, title_en: e.target.value})}
                        className="w-full bg-neutral-900 border border-neutral-800 rounded-lg px-4 py-3 text-white focus:border-red-600 outline-none"
                    />
                </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div className="space-y-2">
                    <label className="text-xs text-neutral-500 font-bold uppercase">Описание (RU)</label>
                    <textarea 
                        value={currentEvent.description_ru || ''}
                        onChange={e => setCurrentEvent({...currentEvent, description_ru: e.target.value})}
                        rows={4}
                        className="w-full bg-neutral-900 border border-neutral-800 rounded-lg px-4 py-3 text-white focus:border-red-600 outline-none resize-none"
                    />
                </div>
                <div className="space-y-2">
                    <label className="text-xs text-neutral-500 font-bold uppercase">Описание (EN)</label>
                    <textarea 
                        value={currentEvent.description_en || ''}
                        onChange={e => setCurrentEvent({...currentEvent, description_en: e.target.value})}
                        rows={4}
                        className="w-full bg-neutral-900 border border-neutral-800 rounded-lg px-4 py-3 text-white focus:border-red-600 outline-none resize-none"
                    />
                </div>
            </div>

            <div className="space-y-2">
                <label className="text-xs text-neutral-500 font-bold uppercase">Картинка (URL)</label>
                <input 
                    value={currentEvent.image_url || ''}
                    onChange={e => setCurrentEvent({...currentEvent, image_url: e.target.value})}
                    placeholder="https://..."
                    className="w-full bg-neutral-900 border border-neutral-800 rounded-lg px-4 py-3 text-white focus:border-red-600 outline-none"
                />
            </div>
        </div>
    </div>
  );
};

export default HistoryManager;
