import React, { useState } from 'react';
import { Plus, Trash2, Save, ArrowLeft, Loader2, ShoppingBag, Upload, X, HelpCircle, Image as ImageIcon, Video, Database, PenTool } from 'lucide-react';
import { Product, ProductFAQ } from '../types';
import { supabase } from '../supabaseClient';
import { INITIAL_PRODUCTS } from '../constants';

interface MarketplaceManagerProps {
  products: Product[];
  onSave: () => void;
}

const MarketplaceManager: React.FC<MarketplaceManagerProps> = ({ products, onSave }) => {
  const [view, setView] = useState<'list' | 'edit'>('list');
  const [currentProduct, setCurrentProduct] = useState<Partial<Product>>({});
  const [isSaving, setIsSaving] = useState(false);
  const [uploading, setUploading] = useState(false);

  // --- Seed Logic ---
  const handleSeedProducts = async () => {
      if (!window.confirm("Это загрузит демо-товары из констант в базу данных. Продолжить?")) return;
      
      setIsSaving(true);
      try {
          if (!supabase) throw new Error("Нет соединения с базой");

          // Удаляем ID из констант, чтобы база сгенерировала новые
          const productsToInsert = INITIAL_PRODUCTS.map(({ id, ...rest }) => ({
              ...rest,
              // Убедимся, что массивы и JSON корректны
              images: rest.images || [],
              faq: rest.faq || []
          }));

          const { error } = await supabase
            .from('market_shibari')
            .insert(productsToInsert);

          if (error) throw error;
          
          alert("Товары успешно загружены!");
          onSave(); // Обновить список
      } catch (e: any) {
          console.error(e);
          alert("Ошибка импорта: " + e.message);
      } finally {
          setIsSaving(false);
      }
  };

  const startEdit = (product?: Product) => {
    if (product) {
      setCurrentProduct(product);
    } else {
      setCurrentProduct({
        title: '',
        color: '',
        description_short: '',
        description_long: '',
        price: 0,
        images: [],
        faq: [],
        video_url: ''
      });
    }
    setView('edit');
  };

  const handleSave = async () => {
    if (!currentProduct.title) {
      alert("Введите название товара");
      return;
    }

    setIsSaving(true);
    try {
      if (!supabase) throw new Error("No database connection");

      const payload = {
        title: currentProduct.title,
        color: currentProduct.color,
        description_short: currentProduct.description_short,
        description_long: currentProduct.description_long,
        price: currentProduct.price,
        images: currentProduct.images || [],
        video_url: currentProduct.video_url,
        faq: currentProduct.faq || []
      };

      if (currentProduct.id) {
        const { error } = await supabase
          .from('market_shibari')
          .update(payload)
          .eq('id', currentProduct.id);
        if (error) throw error;
      } else {
        const { error } = await supabase
          .from('market_shibari')
          .insert([payload]);
        if (error) throw error;
      }

      onSave();
      setView('list');
    } catch (e: any) {
      console.error("Error saving product:", e);
      // Fallback SQL for table creation if missing
      const repairSql = `
create table if not exists public.market_shibari (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  color text,
  description_short text,
  description_long text,
  price numeric default 0,
  images text[] default '{}',
  video_url text,
  faq jsonb default '[]'
);
alter table public.market_shibari enable row level security;
do $$ begin
  if not exists (select 1 from pg_policies where tablename = 'market_shibari' and policyname = 'Allow all operations') then
    create policy "Allow all operations" on public.market_shibari for all using (true) with check (true);
  end if;
end $$;
      `.trim();
      alert(`Ошибка сохранения: ${e.message}\nЕсли таблицы нет, выполните SQL в Supabase:\n\n${repairSql}`);
    } finally {
      setIsSaving(false);
    }
  };

  const handleDelete = async (id: number) => {
    if (!window.confirm("Удалить товар?")) return;
    try {
      if (supabase) {
        await supabase.from('market_shibari').delete().eq('id', id);
        onSave();
      }
    } catch (e) {
      console.error(e);
    }
  };

  const handleImageUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    if (!e.target.files || !e.target.files.length || !supabase) return;
    setUploading(true);
    
    try {
        const newUrls: string[] = [];
        for (let i = 0; i < e.target.files.length; i++) {
            const file = e.target.files[i];
            const fileExt = file.name.split('.').pop();
            const fileName = `marketplace/${Math.random().toString(36).substring(2)}.${fileExt}`;
            
            const { error } = await supabase.storage.from('Enot').upload(fileName, file);
            if (error) throw error;
            
            const { data } = supabase.storage.from('Enot').getPublicUrl(fileName);
            newUrls.push(data.publicUrl);
        }
        
        setCurrentProduct(prev => ({
            ...prev,
            images: [...(prev.images || []), ...newUrls]
        }));
    } catch (err: any) {
        alert("Ошибка загрузки фото: " + err.message);
    } finally {
        setUploading(false);
    }
  };

  const removeImage = (index: number) => {
    setCurrentProduct(prev => ({
        ...prev,
        images: prev.images?.filter((_, i) => i !== index)
    }));
  };

  const addFaq = () => {
    setCurrentProduct(prev => ({
        ...prev,
        faq: [...(prev.faq || []), { question: '', answer: '' }]
    }));
  };

  const updateFaq = (index: number, field: keyof ProductFAQ, value: string) => {
    setCurrentProduct(prev => {
        const newFaq = [...(prev.faq || [])];
        newFaq[index] = { ...newFaq[index], [field]: value };
        return { ...prev, faq: newFaq };
    });
  };

  const removeFaq = (index: number) => {
    setCurrentProduct(prev => ({
        ...prev,
        faq: prev.faq?.filter((_, i) => i !== index)
    }));
  };

  if (view === 'list') {
    return (
      <div className="space-y-6">
         <div className="flex justify-between items-center">
            <p className="text-neutral-400">Управление товарами в магазине.</p>
            <div className="flex gap-2">
                {products.length === 0 && (
                    <button 
                        onClick={handleSeedProducts}
                        disabled={isSaving}
                        className="bg-neutral-800 hover:bg-neutral-700 text-neutral-300 px-4 py-2 rounded-lg font-medium flex items-center gap-2 transition-colors border border-neutral-700"
                    >
                        {isSaving ? <Loader2 className="w-4 h-4 animate-spin"/> : <Database className="w-4 h-4" />} 
                        Загрузить шаблоны
                    </button>
                )}
                <button 
                    onClick={() => startEdit()}
                    className="bg-red-700 hover:bg-red-600 text-white px-4 py-2 rounded-lg font-medium flex items-center gap-2 transition-colors"
                >
                    <Plus className="w-4 h-4" /> Добавить товар
                </button>
            </div>
        </div>

        {/* Vertical Cards Grid (3x4) */}
        <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
            {products.map(p => (
                <div key={p.id} className="bg-neutral-900 border border-neutral-800 rounded-xl overflow-hidden flex flex-col group relative hover:border-neutral-600 transition-colors">
                     {/* Image 3:4 */}
                     <div className="aspect-[3/4] w-full bg-black relative">
                         {p.images && p.images[0] ? (
                             <img src={p.images[0]} alt="" className="w-full h-full object-cover" />
                         ) : (
                             <div className="w-full h-full flex items-center justify-center text-neutral-700">
                                 <ImageIcon className="w-8 h-8" />
                             </div>
                         )}
                         
                         {/* Overlay actions */}
                         <div className="absolute inset-0 bg-black/60 opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center gap-2">
                             <button onClick={() => startEdit(p)} className="p-3 bg-neutral-900 text-white rounded-full hover:bg-neutral-700 border border-neutral-700 transition-transform hover:scale-110 shadow-xl" title="Редактировать">
                                 <PenTool className="w-5 h-5"/>
                             </button>
                             <button onClick={() => handleDelete(p.id)} className="p-3 bg-red-900 text-white rounded-full hover:bg-red-700 border border-red-800 transition-transform hover:scale-110 shadow-xl" title="Удалить">
                                 <Trash2 className="w-5 h-5"/>
                             </button>
                         </div>
                     </div>
                     
                     {/* Card Content */}
                     <div className="p-3 flex flex-col gap-1">
                         <h4 className="font-bold text-white text-sm line-clamp-1" title={p.title}>{p.title}</h4>
                         <div className="flex justify-between items-center mt-1">
                            <span className="text-xs text-neutral-500 truncate max-w-[60%]">{p.color}</span>
                            <span className="text-xs font-mono font-bold text-neutral-300">${p.price}</span>
                         </div>
                     </div>
                </div>
            ))}
        </div>
      </div>
    );
  }

  return (
    <div className="flex flex-col h-full space-y-6">
      <div className="flex items-center justify-between border-b border-neutral-800 pb-4">
         <button onClick={() => setView('list')} className="text-neutral-400 hover:text-white flex items-center gap-2">
            <ArrowLeft className="w-4 h-4" /> Назад
         </button>
         <button 
            onClick={handleSave} 
            disabled={isSaving}
            className="bg-green-700 hover:bg-green-600 text-white px-6 py-2 rounded-lg font-medium flex items-center gap-2 disabled:opacity-50"
        >
            {isSaving ? <Loader2 className="w-4 h-4 animate-spin"/> : <Save className="w-4 h-4" />}
            Сохранить
        </button>
      </div>

      <div className="flex-1 overflow-y-auto space-y-6 pr-2">
          {/* Main Info */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div className="space-y-4">
                  <input 
                    value={currentProduct.title || ''}
                    onChange={e => setCurrentProduct({...currentProduct, title: e.target.value})}
                    placeholder="Название товара"
                    className="w-full bg-neutral-900 border border-neutral-800 rounded-lg px-4 py-3 text-white focus:border-red-600 outline-none"
                  />
                  <div className="flex gap-4">
                      <input 
                        value={currentProduct.color || ''}
                        onChange={e => setCurrentProduct({...currentProduct, color: e.target.value})}
                        placeholder="Цвет / Вариант"
                        className="flex-1 bg-neutral-900 border border-neutral-800 rounded-lg px-4 py-3 text-white focus:border-red-600 outline-none"
                      />
                      <input 
                        type="number"
                        value={currentProduct.price || ''}
                        onChange={e => setCurrentProduct({...currentProduct, price: parseFloat(e.target.value)})}
                        placeholder="Цена ($)"
                        className="w-32 bg-neutral-900 border border-neutral-800 rounded-lg px-4 py-3 text-white focus:border-red-600 outline-none"
                      />
                  </div>
                  <textarea 
                    value={currentProduct.description_short || ''}
                    onChange={e => setCurrentProduct({...currentProduct, description_short: e.target.value})}
                    placeholder="Краткое описание (для карточки)"
                    rows={2}
                    className="w-full bg-neutral-900 border border-neutral-800 rounded-lg px-4 py-3 text-white focus:border-red-600 outline-none resize-none"
                  />
              </div>
              
              <div className="space-y-4">
                   <div className="flex items-center justify-between">
                       <label className="text-xs font-bold text-neutral-500 uppercase flex items-center gap-2"><ImageIcon className="w-4 h-4"/> Фотографии</label>
                       <label className="cursor-pointer text-xs text-red-500 hover:text-red-400 font-bold flex items-center gap-1">
                           {uploading ? <Loader2 className="w-3 h-3 animate-spin"/> : <Upload className="w-3 h-3"/>} Загрузить
                           <input type="file" multiple accept="image/*" className="hidden" onChange={handleImageUpload} disabled={uploading} />
                       </label>
                   </div>
                   <div className="flex gap-2 overflow-x-auto pb-2 min-h-[80px]">
                       {(currentProduct.images || []).map((img, idx) => (
                           <div key={idx} className="relative w-20 h-20 bg-neutral-900 rounded-lg border border-neutral-800 shrink-0 group">
                               <img src={img} alt="" className="w-full h-full object-cover rounded-lg" />
                               <button onClick={() => removeImage(idx)} className="absolute -top-2 -right-2 bg-red-600 text-white rounded-full p-1 shadow opacity-0 group-hover:opacity-100 transition-opacity">
                                   <X className="w-3 h-3" />
                               </button>
                           </div>
                       ))}
                       {(!currentProduct.images?.length) && <div className="text-neutral-600 text-sm flex items-center">Нет фото</div>}
                   </div>
                   
                   <input 
                    value={currentProduct.video_url || ''}
                    onChange={e => setCurrentProduct({...currentProduct, video_url: e.target.value})}
                    placeholder="Ссылка на видео (YouTube)"
                    className="w-full bg-neutral-900 border border-neutral-800 rounded-lg px-4 py-3 text-white focus:border-red-600 outline-none text-sm"
                  />
              </div>
          </div>

          <textarea 
            value={currentProduct.description_long || ''}
            onChange={e => setCurrentProduct({...currentProduct, description_long: e.target.value})}
            placeholder="Полное описание товара..."
            rows={6}
            className="w-full bg-neutral-900 border border-neutral-800 rounded-lg px-4 py-3 text-white focus:border-red-600 outline-none"
          />

          {/* FAQ Editor */}
          <div className="bg-neutral-900/50 border border-neutral-800 rounded-xl p-4">
              <div className="flex items-center justify-between mb-4">
                  <h4 className="font-bold text-white text-sm flex items-center gap-2"><HelpCircle className="w-4 h-4"/> Частые вопросы (FAQ)</h4>
                  <button onClick={addFaq} className="text-xs text-red-500 hover:text-red-400 font-bold flex items-center gap-1"><Plus className="w-3 h-3"/> Добавить вопрос</button>
              </div>
              <div className="space-y-4">
                  {(currentProduct.faq || []).map((item, idx) => (
                      <div key={idx} className="flex flex-col gap-2 border-b border-neutral-800 pb-4 last:border-0 last:pb-0">
                          <div className="flex gap-2">
                              <input 
                                value={item.question}
                                onChange={e => updateFaq(idx, 'question', e.target.value)}
                                placeholder="Вопрос"
                                className="flex-1 bg-neutral-900 border border-neutral-700 rounded px-3 py-2 text-sm text-white outline-none"
                              />
                              <button onClick={() => removeFaq(idx)} className="text-neutral-500 hover:text-red-500"><Trash2 className="w-4 h-4"/></button>
                          </div>
                          <textarea 
                            value={item.answer}
                            onChange={e => updateFaq(idx, 'answer', e.target.value)}
                            placeholder="Ответ"
                            rows={2}
                            className="w-full bg-neutral-900 border border-neutral-700 rounded px-3 py-2 text-sm text-neutral-300 outline-none resize-none"
                          />
                      </div>
                  ))}
                  {!currentProduct.faq?.length && <div className="text-neutral-500 text-sm text-center py-2">Список пуст</div>}
              </div>
          </div>
      </div>
    </div>
  );
};

export default MarketplaceManager;